In [1]:
from Controller import TraceClassifierController
from Utils.SaveUtils import load_parameters
from Parameters import TrainingParameters
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
# %tensorboard --logdir logs/gradient_tape --host localhost --port 8088

In [3]:
parameters = TrainingParameters()
tf.random.set_seed(parameters.dataset_split_seed)
np.random.seed(parameters.dataset_split_seed)
controller = TraceClassifierController(parameters = parameters)


| Running on /job:localhost/replica:0/task:0/device:CPU:0  

| Preprocessed data loaded successfully: ./datasets/preprocessed/BPI_Challenge_2012_valid_trace/All 


In [4]:
controller.show_model_info()

Model: "baseline_lstm_with_resource_valid_trace_cf"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        multiple                  832       
_________________________________________________________________
embedding_1 (Embedding)      multiple                  9216      
_________________________________________________________________
lstm (LSTM)                  multiple                  8320      
_________________________________________________________________
lstm_1 (LSTM)                multiple                  8320      
_________________________________________________________________
lstm_2 (LSTM)                multiple                  20608     
_________________________________________________________________
lstm_3 (LSTM)                multiple                  8320      
_________________________________________________________________
sequential (Sequential) 

In [5]:
controller.train()


| Training records in logs/gradient_tape/20210626-150644 

| Total epochs: 10 

| Total steps: 8180 

| Start epoch 0 

| Evaluation result | Loss [0.5756] | Accuracy [0.4986]  

| Evaluation result | Loss [0.5022] | Accuracy [0.4996]  

| Evaluation result | Loss [0.3975] | Accuracy [0.7472]  

| Evaluation result | Loss [0.3094] | Accuracy [0.8447]  

| Evaluation result | Loss [0.2157] | Accuracy [0.8949]  

| Evaluation result | Loss [0.1172] | Accuracy [0.9574]  

| Evaluation result | Loss [0.0723] | Accuracy [0.9610]  

| Evaluation result | Loss [0.0548] | Accuracy [0.9624]  

| Evaluation result | Loss [0.0413] | Accuracy [0.9808]  

| Evaluation result | Loss [0.0384] | Accuracy [0.9812]  

| Start epoch 1 

| Evaluation result | Loss [0.0378] | Accuracy [0.9845]  

| Evaluation result | Loss [0.0357] | Accuracy [0.9854]  

| Evaluation result | Loss [0.0355] | Accuracy [0.9841]  

| Evaluation result | Loss [0.0352] | Accuracy [0.9841]  

| Evaluation result | Loss [0.0350]

In [6]:
## Accuracy in first round 0.7595908

In [7]:
###### Save modelz
controller.save_training_result("classify_valid_trace.ipynb")


| Model saved successfully to: ./SavedModels/0.9852_ValidPath_BaselineLSTMWithResource_2021-06-26 17:30:16.618388  


In [8]:
controller.load_trained_model("./SavedModels/0.9860_BPI2012WithResource_BaselineLSTMWithResource_2021-06-25 21:03:20.326179")
caseids, padded_data_traces, lengths, padded_data_resources, batch_amount, padded_target_traces, real_trace = controller.dataset.collate_fn([45])


| Model loaded successfully from: ./SavedModels/0.9860_BPI2012WithResource_BaselineLSTMWithResource_2021-06-25 21:03:20.326179  


In [9]:
controller.model(padded_data_traces, padded_data_resources, batch_amount, training=False)[0]

<tf.Tensor: shape=(1, 17, 1), dtype=float32, numpy=
array([[[ 0.09007662],
        [ 6.913041  ],
        [ 9.894565  ],
        [12.6869    ],
        [12.595566  ],
        [12.267059  ],
        [12.18059   ],
        [12.28367   ],
        [12.347564  ],
        [12.841791  ],
        [13.402487  ],
        [13.357363  ],
        [13.217136  ],
        [13.383248  ],
        [12.936321  ],
        [12.182722  ],
        [11.8540535 ]]], dtype=float32)>

In [10]:
padded_data_traces

array([[ 2, 12,  9, 10,  3, 17,  8, 15, 19, 22, 24, 18, 24, 25, 16,  7,
        25]], dtype=int32)

In [11]:
controller.show_model_info()

Model: "baseline_lstm_with_resource_valid_trace_cf"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        multiple                  832       
_________________________________________________________________
embedding_1 (Embedding)      multiple                  9216      
_________________________________________________________________
lstm (LSTM)                  multiple                  8320      
_________________________________________________________________
lstm_1 (LSTM)                multiple                  8320      
_________________________________________________________________
lstm_2 (LSTM)                multiple                  20608     
_________________________________________________________________
lstm_3 (LSTM)                multiple                  8320      
_________________________________________________________________
sequential (Sequential) 

<tf.Tensor: shape=(1, 17, 1), dtype=float32, numpy=
array([[[ 0.09007662],
        [ 6.913041  ],
        [ 9.894565  ],
        [12.6869    ],
        [12.595566  ],
        [12.267059  ],
        [12.18059   ],
        [12.28367   ],
        [12.347564  ],
        [12.841791  ],
        [13.402487  ],
        [13.357363  ],
        [13.217136  ],
        [13.383248  ],
        [12.936321  ],
        [12.182722  ],
        [11.8540535 ]]], dtype=float32)>

In [12]:
example_activities_input

NameError: name 'example_activities_input' is not defined

In [30]:
controller.model(example_activities_input, example_resources_input, example_amount_input)[0]

<tf.Tensor: shape=(1, 9, 1), dtype=float32, numpy=
array([[[ 0.45503947],
        [ 7.0611873 ],
        [10.051995  ],
        [ 9.633373  ],
        [ 9.78532   ],
        [ 9.926899  ],
        [ 9.713137  ],
        [ 9.791196  ],
        [ 9.96656   ]]], dtype=float32)>

In [31]:
controller.model(tf.one_hot(example_activities_input, depth=len(trainer.model.vocab)), tf.one_hot(example_resources_input, depth=len(trainer.model.resources)), example_amount_input)[0]


| Multiply! 


<tf.Tensor: shape=(1, 9, 1), dtype=float32, numpy=
array([[[ 0.45503947],
        [ 7.0611873 ],
        [10.051995  ],
        [ 9.633373  ],
        [ 9.78532   ],
        [ 9.926899  ],
        [ 9.713137  ],
        [ 9.791196  ],
        [ 9.96656   ]]], dtype=float32)>

In [24]:
example_activities_input

<tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[ 2, 12,  9, 10, 20, 22,  3, 17,  8]], dtype=int32)>

In [21]:
tf.one_hot(example_activities_input, depth=len(trainer.model.vocab))

<tf.Tensor: shape=(1, 9, 26), dtype=float32, numpy=
array([[[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 1

In [22]:
tf.one_hot(example_resources_input, depth=len(trainer.model.resources))

<tf.Tensor: shape=(1, 9, 72), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 

In [29]:
from Controller import TrainingController, TraceClassifierController
from Parameters import TrainingParameters
from Utils.SaveUtils import load_parameters
from Utils.PrintUtils import print_big
import tensorflow as tf
import json
from dice import EventLogDiCE
import numpy as np
import pandas as pd
import time
from Models import DiCEBinaryDefferentiable
from itertools import chain
from IPython.core.display import display, HTML
from Utils.DiCEHelpers import generate_fake_df, get_trace_with_id, get_longest_trace_row, remove_trail_steps, print_model_prediction_result, remove_tags_for_query_instance

folder_path = "./SavedModels/%s" % (
    "0.8264_BPI2012WithResource_BaselineLSTMWithResource_2021-06-18 06:11:10.009443" #AOW
)

### Initialise controllers
parameters_json = load_parameters(folder_path=folder_path)
parameters = TrainingParameters(**parameters_json)
tf.random.set_seed(parameters.dataset_split_seed)
np.random.seed(parameters.dataset_split_seed)
parameters.load_model_folder_path = folder_path
trainer = TrainingController(parameters = parameters)
trainer.show_model_info()

########### Get example data from trainer ###########
ordered_test_idx = (list(trainer.test_dataset.unbatch().as_numpy_iterator()))
ordered_test_idx.sort()
print_big(len(ordered_test_idx), "Test set length")

########## Get longest delcined trace for testing ##########
declined_df = get_trace_with_id(trainer.dataset.df.iloc[ordered_test_idx], trainer.model.vocab.vocab_to_index('A_DECLINED_COMPLETE'))
longest_declined_trace_row = get_longest_trace_row(declined_df)
longest_declined_trace_row

_, example_activities, _, example_resources, example_amount, _ = trainer.dataset.collate_fn([longest_declined_trace_row.index[0]])

tail_length_to_remove = 45
example_idx_activities, example_idx_resources = remove_trail_steps(example_activities, example_resources, tail_length_to_remove)
example_vocab_activities = trainer.model.vocab.list_of_index_to_vocab_2d(example_idx_activities)[0]
print("========================================Trace after substraction========================================")
print(example_vocab_activities)

##### Get model output
example_activities_input = tf.constant(example_idx_activities)
example_resources_input = tf.constant(example_idx_resources)
example_amount_input = tf.constant(example_amount)

predicted_df = print_model_prediction_result(trainer.model, example_activities_input, example_resources_input, example_amount_input)


| Running on /job:localhost/replica:0/task:0/device:CPU:0  

| Preprocessed data loaded successfully: ./datasets/preprocessed/BPI_Challenge_2012_with_resource/AOW 

| Model loaded successfully from: ./SavedModels/0.8264_BPI2012WithResource_BaselineLSTMWithResource_2021-06-18 06:11:10.009443  
Model: "baseline_lstm_with_resource"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      multiple                  832       
_________________________________________________________________
embedding_3 (Embedding)      multiple                  2304      
_________________________________________________________________
lstm_4 (LSTM)                multiple                  24832     
_________________________________________________________________
lstm_5 (LSTM)                multiple                  33024     
_________________________________________________________________
lstm_6 (