In [1]:
from Controller import TrainingController
from Utils.SaveUtils import load_parameters
from Parameters import TrainingParameters
import tensorflow as tf
import numpy as np

In [2]:
####### Show tensorboard
# %load_ext tensorboard
# %tensorboard --logdir logs/gradient_tape
# %tensorboard --logdir logs/gradient_tape --host localhost --port 8088

In [3]:
parameters = TrainingParameters()
tf.random.set_seed(parameters.dataset_split_seed)
np.random.seed(parameters.dataset_split_seed)
trainer = TrainingController(parameters = parameters)


| Running on /job:localhost/replica:0/task:0/device:CPU:0  


In [4]:
trainer.show_model_info()

Model: "base_nn"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
sequential (Sequential)      (1, 1)                    841       
Total params: 841
Trainable params: 713
Non-trainable params: 128
_________________________________________________________________


In [5]:
trainer.train()


| Total epochs: 50 

| Total steps: 350 

| Start epoch 0 

| Start epoch 1 

| Start epoch 2 

| Start epoch 3 

| Start epoch 4 

| Start epoch 5 

| Start epoch 6 

| Start epoch 7 

| Start epoch 8 

| Start epoch 9 

| Start epoch 10 

| Start epoch 11 

| Start epoch 12 

| Start epoch 13 

| Start epoch 14 

| Start epoch 15 

| Start epoch 16 

| Start epoch 17 

| Start epoch 18 

| Start epoch 19 

| Start epoch 20 

| Start epoch 21 

| Start epoch 22 

| Start epoch 23 

| Start epoch 24 

| Start epoch 25 

| Start epoch 26 

| Start epoch 27 

| Start epoch 28 

| Start epoch 29 

| Start epoch 30 

| Start epoch 31 

| Start epoch 32 

| Start epoch 33 

| Start epoch 34 

| Start epoch 35 

| Start epoch 36 

| Start epoch 37 

| Start epoch 38 

| Start epoch 39 

| Start epoch 40 

| Start epoch 41 

| Start epoch 42 

| Evaluation result | Loss [4.7759] | Accuracy [0.6900]  

| Start epoch 43 

| Start epoch 44 

| Start epoch 45 

| Start epoch 46 

| Start epoch 4

In [6]:
###### Save modelz
trainer.save_training_result("train.ipynb")


| Save mean and vairance 

| Model saved successfully to: ./SavedModels/0.7700_Diabetes_BaseNNModel_2021-05-30 04:41:24.179089  


In [11]:
trainer.load_trained_model("./SavedModels/0.7700_Diabetes_BaseNNModel_2021-05-30 04:41:24.179089")


| Model loaded successfully from: ./SavedModels/0.7700_Diabetes_BaseNNModel_2021-05-30 04:41:24.179089  


In [8]:
trainer.model.mean_

<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([  4.045     , 124.88125   ,  69.725     ,  21.53375   ,
        88.29      ,  32.617374  ,   0.51100874,  33.815     ],
      dtype=float32)>

In [9]:
trainer.model.var_

<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([1.2412975e+01, 1.0790321e+03, 3.9889938e+02, 2.6584885e+02,
       1.5491934e+04, 6.2756962e+01, 1.3522759e-01, 1.3059077e+02],
      dtype=float32)>

In [10]:
tf.constant(tf.Variable(trainer.model.var_))

<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([1.2412975e+01, 1.0790321e+03, 3.9889938e+02, 2.6584885e+02,
       1.5491934e+04, 6.2756962e+01, 1.3522759e-01, 1.3059077e+02],
      dtype=float32)>