In [1]:
import tensorflow as tf

In [4]:
testing_data = tf.random.normal((1, 10))

In [5]:
from LINDA_BN.permute import *

NameError: name 'torch' is not defined

In [19]:
tf.random.uniform((200), minval=[1,200], maxval=[3,400])

InvalidArgumentError: shape must be a vector of {int32,int64}, got shape [] [Op:RandomUniform]

In [24]:
tf.constant([2,3,4]).shape[-1]

3

In [25]:

def generate_permutation_for_numerical_all_dim(input_data: tf.Tensor, num_samples, variance=0.1, clip_permutation: bool = True):
    '''
    [input_data]: Normalised data. should be a 1-D tensor.
    --------------------------
    Return: all permutations.
    '''
    if clip_permutation:
        max_range = tf.clip_by_value(input_data + variance, -0.999999, 1)
        min_range = tf.clip_by_value(input_data - variance, -1, 0.999999)
    else:
        max_range = input_data + variance
        min_range = input_data - variance

    return tf.random.uniform((num_samples,  input_data.shape[-1]), minval=min_range.numpy(), maxval=max_range.numpy())

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([-1.4710652, -0.5391804,  0.7994068, -1.9482434, -1.4278344],
      dtype=float32)>

In [37]:
generate_permutation_for_numerical_all_dim(tf.random.normal((5,)), 900).shape

TensorShape([900, 5])

In [38]:
import numpy as np

In [54]:
t = tf.random.normal((5,))

In [55]:
t

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([ 2.2689524 ,  0.34611565, -0.03903288, -0.13670799,  0.7556403 ],
      dtype=float32)>

In [57]:
generate_permutations_for_normerical_all_dim_normal_dist(t, 900, variance=0.1)

<tf.Tensor: shape=(900, 5), dtype=float32, numpy=
array([[ 2.5608053 ,  0.39784074, -0.06291838, -0.18098643,  0.42030615],
       [ 1.9980717 ,  0.03828368,  0.78565264, -0.7097651 ,  0.4862226 ],
       [ 2.31737   ,  0.688362  , -0.20104396, -0.37160102,  0.9758958 ],
       ...,
       [ 2.113659  , -0.1092588 , -0.03049222, -0.1437498 ,  1.0637769 ],
       [ 2.0207193 ,  0.86569697,  0.2589068 ,  0.25518054,  0.4035336 ],
       [ 2.4714918 ,  0.67769325,  0.03874832, -0.33656847,  0.6350397 ]],
      dtype=float32)>

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ -6.2759695 , 474.02734   ],
       [ 10.384821  , 515.10565   ],
       [  4.4600344 , 530.63257   ],
       [ -0.89876175, 511.6428    ],
       [ 26.774948  , 485.98148   ]], dtype=float32)>